import js from '@eslint/js';
import globals from 'globals';

export default [
    // Global ignores — applies to all subsequent config entries.
    {
        ignores: [
            'node_modules/**',
            '.claude/**',         // Agent worktrees and session data
            'scripts/**',         // Dev utilities: bump-version, generate-roster-members
            'e2e/**',             // Playwright smoke tests — Node + Playwright globals, not browser
            'playwright.config.mjs', // Playwright config — Node globals (process.env)
            'playwright.csp.mjs',    // Playwright config (CSP proof) — Node globals (process.env)
            'playwright.visual.mjs', // Playwright config (visual baselines) — Node globals (process.env)
            '*.test.mjs',         // Test files — use test-runner globals, not browser
            '*.test.js',
            'purify.es.mjs',      // Vendor bundle — do not lint
            'service-worker.js',  // SW global scope: self, caches, clients (non-browser)
            'generate-sri.mjs',   // Dev utility
            'playwright-report/**', // Generated by Playwright — not source
            'test-results/**',      // Generated by Playwright — not source
        ],
    },
    // ESLint recommended baseline.
    js.configs.recommended,
    // App-specific language options and rule overrides.
    {
        files: ['**/*.js', '**/*.mjs'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                ...globals.browser,
            },
        },
        rules: {
            // Catch bindings and vars named _ are intentionally unused (no-op catch / destructure discard).
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
            // Intentional empty catch blocks are allowed; empty function bodies are not.
            'no-empty': ['error', { allowEmptyCatch: true }],
            'no-console': 'off',
        },
    },
    // mammoth is loaded via CDN <script> in admin.html — not an ES module import.
    {
        files: ['huddle.js'],
        languageOptions: {
            globals: { mammoth: 'readonly' },
        },
    },
    // Cloud Functions: CommonJS modules running in Node.js, not a browser environment.
    // Previously excluded from linting; now covered to catch bugs in the most
    // security-sensitive code (auth checks, push fan-out, roster AI pipeline).
    {
        files: ['functions/**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'commonjs',
            globals: {
                ...globals.node,
            },
        },
        rules: {
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
            'no-empty': ['error', { allowEmptyCatch: true }],
            'no-console': 'off',
        },
    },
];
