import js from '@eslint/js';
import globals from 'globals';

export default [
    // Global ignores — applies to all subsequent config entries.
    {
        ignores: [
            'node_modules/**',
            '.claude/**',         // Agent worktrees and session data
            'experiments/**',     // One-off proofs driven from Node (Playwright + process.env), not app code
            'docs/proposals/tooling/**', // Link-proposal search + PDF render, driven from Node — not app code
            'purify.es.mjs',      // Vendor bundle — do not lint
            'playwright-report/**', // Generated by Playwright — not source
            'test-results/**',      // Generated by Playwright — not source
        ],
    },
    // ESLint recommended baseline.
    js.configs.recommended,
    // App-specific language options and rule overrides.
    {
        files: ['**/*.js', '**/*.mjs'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                ...globals.browser,
            },
        },
        rules: {
            // Catch bindings and vars named _ are intentionally unused (no-op catch / destructure discard).
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
            // Intentional empty catch blocks are allowed; empty function bodies are not.
            'no-empty': ['error', { allowEmptyCatch: true }],
            'no-console': 'off',
        },
    },
    // mammoth is loaded via CDN <script> in admin.html — not an ES module import.
    {
        files: ['huddle.js'],
        languageOptions: {
            globals: { mammoth: 'readonly' },
        },
    },
    // Cloud Functions: CommonJS modules running in Node.js, not a browser environment.
    // Previously excluded from linting; now covered to catch bugs in the most
    // security-sensitive code (auth checks, push fan-out, roster AI pipeline).
    {
        files: ['functions/**/*.js'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'commonjs',
            globals: {
                ...globals.node,
            },
        },
        rules: {
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
            'no-empty': ['error', { allowEmptyCatch: true }],
            'no-console': 'off',
        },
    },

    // Shared TEST FIXTURES: ES modules running in Node, so they need node globals (Buffer) with
    // `sourceType: 'module'` — the Cloud Functions block above is the same environment but
    // CommonJS, and folding these in there makes every `export` a parsing error.
    {
        files: ['test-fixtures/**/*.mjs'],
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                ...globals.node,
            },
        },
    },

    // ── THE CODE THAT CHECKS THE CODE (v24.28 review) ─────────────────────────────────────────
    // Tests, e2e specs, scripts, the Playwright configs and the service worker used to be IGNORED
    // outright, each with a note naming the globals it needed rather than supplying them. That left
    // the highest-outage-risk file in the repo (service-worker.js) and every guard in the estate
    // unlinted: an undefined name, a useless assignment or an unused label went unseen in exactly
    // the files a reader trusts to be right. Each now gets the environment it actually runs in.
    {
        // Node test runner + Playwright. BOTH global sets: a test stubs `document`/`window` onto
        // globalThis and then reads them bare, and an e2e spec's page.evaluate() callback runs in the
        // browser. Unused bindings are OFF here — fixtures and destructured harness returns are
        // routinely partial, and a warning (which --max-warnings=0 makes fatal) would push authors
        // to delete documentation-by-destructuring rather than find a bug.
        files: ['**/*.test.mjs', '**/*.test.js', 'e2e/**/*.js', 'e2e/**/*.mjs', 'playwright*.mjs'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: { ...globals.node, ...globals.browser },
        },
        rules: { 'no-unused-vars': 'off' },
    },
    {
        files: ['scripts/**/*.mjs', 'generate-sri.mjs'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: { ...globals.node },
        },
    },
    {
        // A classic worker SCRIPT, not a module: self/caches/clients, and AbortController, which the
        // serviceworker set in this `globals` version omits although every engine exposes it there.
        files: ['service-worker.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'script',
            globals: { ...globals.serviceworker, AbortController: 'readonly' },
        },
    },
];
